### ISSUE TITLE
Improved Asset build

### ISSUE THREAD

**Issue by jacmoe** [yiisoft-contrib/yiiframework.com#130]
I want to modernize the asset build pipeline a bit, and I am planning to use the following directory layout:

```
assets
    AppAsset.php
    dist
        js
        css
    src
        js
        scss

```

The `dist` directory is going to be ignored by Git and deleted upon each `gulp build` run.

The AppAsset references the generated files in `dist` and my thought is to configure the AssetManager component like follows:

            'linkAssets' => true,
            'appendTimestamp' => true,

That means that the generated files in `dist` is what is being served - symlinked into the assets dir in `web`

I am also going to introduce a flag for Gulp called `production` that will minimize / uglify - this means that the Gulp script will now only perform one set of operations depending on the production flag, and that makes it much faster.

Finally, all paths, files, etc. will go into a `config.yml` and this means that the `all.json` in 'js' is no longer needed.

And Gulp version is bumped to Gulp 4 (beta) because it is better :)

See [Bugitor](https://github.com/jacmoe/bugitor) for an example of a project where the above build tool-chain layout / thingie has been applied.

The main reason why I am asking is that it involves the AssetManager linkAssets configuration setting.

Is that acceptable?

Do not hesitate to ask any questions. :)

**Comment by jacmoe** [comment]
This is how the new gulpfile will look like (more or less):

```
// Load plugins
var gulp = require('gulp');
var $ = require('gulp-load-plugins')();
var browsersync = require('browser-sync');
var rimraf = require('rimraf');
var yargs = require('yargs');
var yaml = require('js-yaml');
var fs = require('fs');

// Check for --production flag
const PRODUCTION = !!(yargs.argv.production);

// Load settings from settings.yml
var config = loadConfig();

function loadConfig() {
  ymlFile = fs.readFileSync('config.yml', 'utf8');
  return yaml.load(ymlFile);
}


var sassOptions = {
  errLogToConsole: true,
  outputStyle: 'expanded',
  includePaths: config.PATHS.sass
};

var autoprefixerOptions = {
  browsers: config.COMPATIBILITY
};


// Styles
function styles() {
  return gulp.src(config.PATHS.src +'/scss/all.scss')
    .pipe($.sourcemaps.init())
    .pipe($.sass(sassOptions).on('error', $.sass.logError))
    .pipe($.autoprefixer(autoprefixerOptions))
    .pipe($.if(PRODUCTION, $.rename({ suffix: '.min' })))
    .pipe($.if(PRODUCTION, $.cssnano()))
    .pipe($.if(!PRODUCTION, $.sourcemaps.write('.', { sourceRoot: '../../assets/src/scss/' })))
    .pipe(gulp.dest(config.PATHS.dist + '/css'))
    .pipe($.notify({ message: 'Styles task complete' }));
};

// Scripts
function scripts() {
  return gulp.src(config.PATHS.javascript)
    .pipe($.sourcemaps.init())
    .pipe($.concat('all.js'))
    .pipe($.if(PRODUCTION, $.rename({ suffix: '.min' })))
    .pipe($.if(PRODUCTION, $.uglify()))
    .pipe($.if(!PRODUCTION, $.sourcemaps.write('.', { sourceRoot: '../../assets/src/js/' })))
    .pipe(gulp.dest(config.PATHS.dist + '/js'))
    .pipe($.notify({ message: 'Scripts task complete' }));
};

// Copy fonts
function fonts() {
  return gulp.src(config.PATHS.fonts)
    .pipe(gulp.dest(config.PATHS.dist + '/fonts'));
};

// Clean
function clean(done) {
    rimraf(config.PATHS.dist, done);
}

// The main build task
gulp.task('build', gulp.series(
  clean,
  gulp.parallel(styles, scripts, fonts)
));

// Watch
function watch() {

  // Initialize Browsersync
  browsersync.init({
    proxy: config.PROXY
  });

  // Watch .scss files
  gulp.watch(config.PATHS.src + '/scss/**/*.scss', styles);

  // Watch .js files
  gulp.watch(config.PATHS.src + '/js/**/*.js', scripts);

  // Watch any view files in 'views', reload on change
  gulp.watch(['views/**/*.php']).on('change', browsersync.reload);

  // Watch any files in 'assets/dist', reload on change
  gulp.watch([config.PATHS.dist + '/js/*']).on('change', browsersync.reload);
  gulp.watch([config.PATHS.dist + '/css/*']).on('change', browsersync.reload);
};

// Default task runs build and then watch
gulp.task('default', gulp.series('build', watch));

// Export these function to the Gulp client
gulp.task('clean', clean);
gulp.task('fonts', fonts);
gulp.task('styles', styles);
gulp.task('scripts', scripts);

```

And an example `config.yml` : 
```
# Your project's server will run on proxy
PROXY: "https://bugitor.dev"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets/dist"
  # Path to source folder
  src: "assets/src"
  # Paths to fonts
  fonts:
    - "vendor/bower/font-awesome/fonts/**/*"
    - "vendor/bower/bootstrap/fonts/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "vendor/bower/bootstrap-sass/assets/stylesheets"
    - "vendor/bower/font-awesome/scss"
    - "vendor/bower/sass-rem"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    - "vendor/bower/jquery/dist/jquery.js"
    - "vendor/bower/bootstrap-sass/assets/javascripts/bootstrap.js"
    - "vendor/yiisoft/yii2/assets/yii.js"
    - "vendor/yiisoft/yii2/assets/yii.validation.js"
    - "vendor/yiisoft/yii2/assets/yii.activeForm.js"
    # Paths to your own project code are here
    - "assets/src/js/!(custom).js"
    - "assets/src/js/custom.js"

```
