### ISSUE TITLE
SideNav in mobile menu

### ISSUE THREAD

**Issue by OndrejVasicek** [yiisoft-contrib/yiiframework.com#293]
Hi guys. The new websites are great.
I've found one bug on mobiles.

The sideNav menu is broken/cut off - [link to image](https://lh3.googleusercontent.com/2yy_Ci4nkuv4-Lf7jdvk9AHGeDzX9vxtElfxP0jFq-91NS1A6bNWtxls9IeuTm5P-BQIaDkvuAw1-Kww2VAC4KRQlUGmcdUsstUu_6suH-4WI3RKs09KYMXa0fMqguAgwu65hNixFyrcipC5xYG_k_l6TMQRJNhRJU5RWgKKpueqDDfvnbpmxqYZnMBgAEACkYPKG7sIVBV6O1VheQnJ8AuXS1P8izwQe4ii8w0pU8wiuhSicD9XA27dEKUzcJXQLe7-Tb2MmmpgnBRIxhFNxn3By8TnV69nyHQLE0Y6-3nUwOLBkkH-jk_RzRLUKX7k5fyJywXXVsFJhtwx2uqLu-3E3AhcpCa9FfxHW4r2zYWuQMIIdiWFcD3gWZLWYUrV7JVcXliNzn1tPFvIJtxEkxv3T3JpNMG39jTJO2XIoKH9Gb4CuxY4vBrN0oT1dnSU_944sa9G97vO-s53NA194hviP_o70ifFbYZKdyQUhrAKMHSkG1k4lgLq5upjiPMTHrnjLyJuheaB5WhqNp05n3N4pHDgHPJIRsj0XNpQWXAkH7IQAJlh9FoEG_GKPc1hvPfoV_6jsKeFRTZiz2U84J0FlpvLo8UBz2WjncKgRapZhRqwJq_TpuelvWC1KDfbkflLeOISV6M8lJDPgWXmUiJiZjmjxkjW6w=w567-h1134-no)

**Comment by Eseperio** [comment]
Currently in **_offcanvas.scss** offset canvas menu is moved with percent. That is wrong, because the size is not relative to the window. That is why it overflows. As a solution replace the percent with `viewWidth` units. I have tested and works perfect. 
```scss
.row-offcanvas
  .sidenav-offcanvas {
    left: -50vw; /* 6 columns */
  }

  .row-offcanvas.active {
    left: 50vw; /* 6 columns */
  }

  .sidenav-offcanvas {
    position: absolute;
    top: 0;
    width: 50vw; /* 6 columns */
  }
```
